# Rerun `pre-commit install` after every update of this file
repos:
# -   repo: https://github.com/antonbabenko/pre-commit-terraform
#     rev: v1.77.0
#     hooks:
#     -   id: terraform_fmt
#     -   id: terraform_validate
-   repo: local
    hooks:
    -   id: terraform_apply
        name: terraform_apply
        #entry: -v ${PWD}:/app --workdir="/app" -e TF_VAR_subscriptionId="$Env:XYZ" docker.io/hashicorp/terraform:1.3.6 apply --var-file="terraform.tfvars.example" -input=false
        entry: --workdir="/src" zenika/terraform-azure-cli pwd > pwd.out
        language: docker_image
# -   repo: local
#     hooks:
#     -   id: terraform_apply
#         name: terraform_apply
#         entry: ./hooks/validate_tfvars.sh
#         language: docker
#         files: Dockerfile
# -   id: terraform_apply
#     name: terraform_apply
#     entry: ./hooks/validate_tfvars.sh
#     language: docker
#     files: \.txt$
